\documentclass{article}

\begin{document}

\section{Install apps}

\begin{enumerate}
\item R
\item RStudio
\item MikTex
\end{enumerate}

\section{Packages}

\begin{itemize}
\item knitr
\item tinytex
\end{itemize}

\section{Example with R}

<<>>=
x <- rnorm(500, 0, 1)
y <- rnorm(500, 0, 1)

summary(x)

plot(x,y)

plot(density(y))
@

\section{Important and Mandatory!}

\Huge Don't forget to subscribe! :)

\end{document}
